### PR TITLE
[JBEE-196] Fix scopes (EE 8)

### PR DESCRIPTION
**Pull request by rdicroce**

### CODE REVIEW

**Comment by rdicroce** [comment]
How does it make consuming more problematic in most scenarios?

The way it is now is broken in a critical scenario (which is also the only one I need it to work in): when used to pull in all of the EE spec JARs.

That is, when you do this:

```
		<dependency>
			<groupId>org.jboss.spec</groupId>
			<artifactId>jboss-javaee-8.0</artifactId>
			<version>1.0.0.Alpha1</version>
			<type>pom</type>
			<scope>provided</scope>
		</dependency>
```

**Comment by ctomc** [comment]
In most cases users that develop war/ear apps that are deployed to app server use this deps.
And in most cases they would forget to manually set scope to provided which would result in this spec api jars to be bundled in deployment itself which in many cases leads to problems with deployment. It can also result in non predictable behavior as some api classes  get loaded from app server and others from deployment.

**Comment by ctomc** [comment]
Btw for your use case i think you are looking for scope=import to get this deps imported.

**Comment by rdicroce** [comment]
> In most cases users that develop war/ear apps that are deployed to app server use this deps.

That is exactly what I'm trying to do. I'm developing a WAR. My goal is to add one dependency to my POM that causes all of the EE API JARs to be put on my classpath with provided scope. The way that I've always done this, up to now, has been to put jboss-javaee-N.0 in my POM under dependencies with provided scope. That is, I'm using it as an aggregator. This causes all of the APIs to be available at compile time, but correctly prevents them from getting included in my deployment.

But now, for some reason, 4 dependencies out of 34 are provided scope in jboss-javaee. Why do these 4 have provided scope while the other 30 have compile scope? I don't see any pattern to it, and no dependencies were provided scope in jboss-javaee-7.0 version 1.0.4. These 4 dependencies suddenly became provided scope for no apparent reason in version 1.1.0, which has now propagated forward into jboss-javaee-8.0. 

AFAICT there is currently no way to achieve my goal:

- Putting jboss-javaee in my POM under dependencyManagement with scope import does nothing since that doesn't cause anything to actually be added to my classpath. In that scenario, I'm not using jboss-javaee as an aggregator, so I would have to manually add every spec JAR dependency to my POM, which defeats the purpose of having jboss-javaee in the first place.
- Putting jboss-javaee in my POM under dependencies with scope compile is (I think) what you described in your last comment. That means I end up with 30 API JARs in my WAR, which is wrong, and 4 API JARs are still completely missing because transitive provided-scoped dependencies do not get added to the classpath no matter what scope the direct dependency is.

So this PR simply fixes those 4 dependencies, which means a provided-scope dependency on jboss-javaee does what it's supposed to. A compile-scoped dependency on jboss-javaee is wrong regardless of whether this PR gets merged or not, and this PR has no impact if jboss-javaee is import-scoped.

**Pull request merged**
